In [2]:
# Import all the given datasets and explore shape and size
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas_profiling

In [64]:
# Import all the given datasets and explore shape and size
company=pd.read_excel('Part2 - Company.xlsx')

company.shape
company.head(40)

A    B    C    D    Quality
0    47   27   45  108  Quality A
1   174  133  134  166  Quality B
2   159  163  135  131        NaN
3    61   23    3   44  Quality A
4    59   60    9   68  Quality A
5   153  140  154  199        NaN
6    34   28   78   22  Quality A
7   191  144  143  154        NaN
8   160  181  194  178  Quality B
9   145  178  158  141        NaN
10   76   94  107   37  Quality A
11  138  200  153  192  Quality B
12   27  106   57   37  Quality A
13   45   76   56   57  Quality A
14  186  142  146  174        NaN
15  196  145  166  132  Quality B
16    4   61   72   98  Quality A
17   96  109   75   34  Quality A
18  167  171  163  191        NaN
19  196  178  165  177  Quality B
20  159  181  142  166  Quality B
21    5  100   32  110  Quality A
22    3   63  109   67  Quality A
23  171  185  181  183        NaN
24  101  104   95   49  Quality A
25  103   74   59   17  Quality A
26  170  153  181  176  Quality B
27  193  169  199  155        NaN
28   85   58   44   32  Quality A
29   29   49    6   35        NaN
30  135  163  194  168  Quality B
31  142  159  176  150  Quality B
32  161  138  143  139        NaN
33  170  174  190  181  Quality B
34  183  142  164  186  Quality B
35  181  147  174  130        NaN
36  185  168  160  151  Quality B
37  132  157  174  138  Quality B
38   44  104    8   21  Quality A
39  102    5   59   72  Quality A

In [12]:
company_class= company.groupby(['Quality'])
company_class.count()

A   B   C   D
Quality                  
Quality A  26  26  26  26
Quality B  17  17  17  17

In [13]:
# SO AS WE CAN SEE FROM THIS DATA, THERE ARE 2 QUALITIES THAT ARE AVAILABLEIN THE
# COMPANY QUALITY A AND QUALITY B. SO OUT OF 61 DATA POINTS (26+17=43) 43 DATAPOINTS
# HAVE THE QUALITY AND THE REMAINING 18 POINTS ARE MISSING THE QUALITY
# THE STRATEGY EMPLOYED WILL BE ABLE TO BUILD A CLASSIFICATION ALGORITHM LIKE 
# SVM OR KNN OR LOGISTIC TO BE ABLE TO DECIDE THE QUALITY OF THE WINE

In [57]:
nan_values=company[company['Quality'].isnull()]
print (nan_values)
nan_values.shape
nan_values_X=nan_values.drop(['Quality'],axis=1)
print(nan_values_X)

      A    B    C    D Quality
2   159  163  135  131     NaN
5   153  140  154  199     NaN
7   191  144  143  154     NaN
9   145  178  158  141     NaN
14  186  142  146  174     NaN
18  167  171  163  191     NaN
23  171  185  181  183     NaN
27  193  169  199  155     NaN
29   29   49    6   35     NaN
32  161  138  143  139     NaN
35  181  147  174  130     NaN
40  179  143  189  177     NaN
46  197  173  165  197     NaN
52  188  178  175  162     NaN
57  137  182  165  199     NaN
58   88   39    9  102     NaN
59  180  157  192  198     NaN
60  157  135  135  156     NaN
      A    B    C    D
2   159  163  135  131
5   153  140  154  199
7   191  144  143  154
9   145  178  158  141
14  186  142  146  174
18  167  171  163  191
23  171  185  181  183
27  193  169  199  155
29   29   49    6   35
32  161  138  143  139
35  181  147  174  130
40  179  143  189  177
46  197  173  165  197
52  188  178  175  162
57  137  182  165  199
58   88   39    9  102
59  180  157  192  1

In [25]:
company_data=company.drop(company.index[[2,5,7,9,14,18,23,27,29,32,35,40,46,52,57,58,59,60]])

In [27]:
company_data.head(57)

A    B    C    D    Quality
0    47   27   45  108  Quality A
1   174  133  134  166  Quality B
3    61   23    3   44  Quality A
4    59   60    9   68  Quality A
6    34   28   78   22  Quality A
8   160  181  194  178  Quality B
10   76   94  107   37  Quality A
11  138  200  153  192  Quality B
12   27  106   57   37  Quality A
13   45   76   56   57  Quality A
15  196  145  166  132  Quality B
16    4   61   72   98  Quality A
17   96  109   75   34  Quality A
19  196  178  165  177  Quality B
20  159  181  142  166  Quality B
21    5  100   32  110  Quality A
22    3   63  109   67  Quality A
24  101  104   95   49  Quality A
25  103   74   59   17  Quality A
26  170  153  181  176  Quality B
28   85   58   44   32  Quality A
30  135  163  194  168  Quality B
31  142  159  176  150  Quality B
33  170  174  190  181  Quality B
34  183  142  164  186  Quality B
36  185  168  160  151  Quality B
37  132  157  174  138  Quality B
38   44  104    8   21  Quality A
39  102    5   59   72  Quality A
41   73   22   83   31  Quality A
42   48   68   98   51  Quality A
43  169  184  200  133  Quality B
44   22    9   25   76  Quality A
45   44   90    6    8  Quality A
47   28   91   17   17  Quality A
48  197  161  182  198  Quality B
49  136  199  189  141  Quality B
50   47   44   66   41  Quality A
51  110   33   76    3  Quality A
53   91   13   14   88  Quality A
54   70   96   70  103  Quality A
55  103   60   15   56  Quality A
56  200  186  185  179  Quality B

In [39]:
#Label Encoding
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
#Assigning numerical values and storing in another column
company_data['Quality_Cat']=labelencoder.fit_transform(company_data['Quality'])
company_data_X=company_data.drop(['Quality','Quality_Cat'],axis=1)
company_data_Y=company_data['Quality_Cat']
company_data_Y

0     0
1     1
3     0
4     0
6     0
8     1
10    0
11    1
12    0
13    0
15    1
16    0
17    0
19    1
20    1
21    0
22    0
24    0
25    0
26    1
28    0
30    1
31    1
33    1
34    1
36    1
37    1
38    0
39    0
41    0
42    0
43    1
44    0
45    0
47    0
48    1
49    1
50    0
51    0
53    0
54    0
55    0
56    1
Name: Quality_Cat, dtype: int32

In [1]:
# Let us use an SVM model to build a model from the data which has output already
# and then we will use it to predict the output in the other dataset.
# Let us first scale the data
from sklearn.model_selection import train_test_split
company_data_X_train, company_data_X_test, y_train,y_test= train_test_split(company_data_X,company_data_Y,test_size=0.3,random_state=1)

from scipy.stats import zscore

scaled_company_data_X_train=company_data_X_train.apply(zscore)
scaled_company_data_X_test=company_data_X_test.apply(zscore)
scaled_company_data_X_train.head()

NameError: name 'company_data_X' is not defined

In [61]:
from sklearn import svm
from sklearn import metrics
SVM_Model = svm.SVC(C=3, kernel='rbf',probability=True)
SVM_Model.fit(scaled_company_data_X_train,y_train)
y_predict_SVM=SVM_Model.predict(scaled_company_data_X_test)
print(metrics.classification_report(y_test,y_predict_SVM))
print(metrics.confusion_matrix(y_test,y_predict_SVM))
y_predict_SVM

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         5

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13

[[8 0]
 [0 5]]


array([0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0])

In [62]:
scaled_company_data_X_test

A         B         C         D
4  -0.688574 -0.666631 -1.295169 -0.501439
3  -0.649739 -1.296591 -1.380277 -0.917527
34  1.719194  0.729496  0.903454  1.544327
54 -0.474981 -0.053697 -0.429905  0.105356
24  0.126960  0.082510 -0.075288 -0.830842
42 -0.902166 -0.530424 -0.032734 -0.796168
31  0.923077  1.018938  1.073670  0.920195
49  0.806572  1.699975  1.258071  0.764162
44 -1.407021 -1.534955 -1.068215 -0.362743
26  1.466767  0.916782  1.144594  1.370957
30  0.787155  1.087041  1.328994  1.232261
47 -1.290516 -0.138827 -1.181692 -1.385627
41 -0.416729 -1.313617 -0.245504 -1.142908

In [82]:
# Use this model to predict the result for the rows where the Quality is not
# filled
from scipy.stats import zscore
scaled_nan_values_X=nan_values_X.apply(zscore)
y_predict_SVM_final=SVM_Model.predict(scaled_nan_values_X)
y_predict_SVM_final

array([0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [69]:
# Model -1 Logistic Regression
# Let us fit the scaled data with these new models and check the accuracy
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver="liblinear")
model.fit(scaled_company_data_X_train,y_train)

#predict on the Test Data
y_predict_Logistic = model.predict(scaled_company_data_X_test)
print(metrics.classification_report(y_test,y_predict_Logistic))
print(metrics.confusion_matrix(y_test,y_predict_Logistic))
y_predict_Logistic

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00         5

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13

[[8 0]
 [0 5]]


array([0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0])

In [81]:
# Use this model to predict the result for the rows where the Quality is not
# filled
from scipy.stats import zscore
scaled_nan_values_X=nan_values_X.apply(zscore)
y_predict_Logistic_final=model.predict(scaled_nan_values_X)
y_predict_Logistic_final

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [83]:
scaled_company_data_X_test

A         B         C         D
4  -0.688574 -0.666631 -1.295169 -0.501439
3  -0.649739 -1.296591 -1.380277 -0.917527
34  1.719194  0.729496  0.903454  1.544327
54 -0.474981 -0.053697 -0.429905  0.105356
24  0.126960  0.082510 -0.075288 -0.830842
42 -0.902166 -0.530424 -0.032734 -0.796168
31  0.923077  1.018938  1.073670  0.920195
49  0.806572  1.699975  1.258071  0.764162
44 -1.407021 -1.534955 -1.068215 -0.362743
26  1.466767  0.916782  1.144594  1.370957
30  0.787155  1.087041  1.328994  1.232261
47 -1.290516 -0.138827 -1.181692 -1.385627
41 -0.416729 -1.313617 -0.245504 -1.142908

In [ ]:
# Hence we can see that both the models are giving very similar results